# Generated by Django 6.0.5 on 2026-05-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrope', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsubmission',
            options={},
        ),
        migrations.RemoveField(
            model_name='savedsubmission',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='savedsubmission',
            name='user',
        ),
        migrations.AlterField(
            model_name='savedsubmission',
            name='raw_input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savedsubmission',
            name='results',
            field=models.TextField(),
        ),
    ]
